# Generated by Django 4.2.7 on 2023-11-23 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_stripe_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('invoice_number', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=1000000)),
                ('comment', models.TextField()),
                ('discount', models.FloatField(blank=True, default=0, max_length=2)),
                ('mode', models.CharField(choices=[('CIB', 'CIB'), ('EDAHABIA', 'EDAHABIA')], default='EDAHABIA', max_length=25)),
                ('status', models.CharField(choices=[('expired', 'EXPIRED'), ('progress', 'IN PROGRESS'), ('paid', 'PAID'), ('canceled', 'CANCELED'), ('failed', 'FAILED')], default='progress', max_length=25)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('client', models.CharField(max_length=255)),
                ('client_email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
