# Generated by Django 4.2.7 on 2023-11-24 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
